os: osx
language: objective-c
osx_image: xcode11.6
before_install: true
install: true
branches:
  only:
    - master
    - main
script:
  - script/build
xcode_workspace: ReactiveObjC.xcworkspace
jobs:
  include:
    - xcode_scheme: ReactiveObjC-iOS
      env:
        - XCODE_SDK=iphonesimulator
        - XCODE_ACTION=test
        - XCODE_DESTINATION="platform=iOS Simulator,name=iPhone 11"
    - xcode_scheme: ReactiveObjC-tvOS
      env:
        - XCODE_SDK=appletvsimulator
        - XCODE_ACTION=test
        - XCODE_DESTINATION="platform=tvOS Simulator,name=Apple TV"
    - xcode_scheme: ReactiveObjC-macOS
      env:
        - XCODE_SDK=macosx
        - XCODE_ACTION=test
        - XCODE_DESTINATION="platform=macOS,arch=x86_64"
    - script:
      - gem install cocoapods --pre
      - pod repo update --silent
      - pod lib lint ReactiveObjC.podspec
      env:
        - JOB=PODSPEC
notifications:
  email: false
  slack:
    secure: C9QTry5wUG9CfeH3rm3Z19R5rDWqDO7EhHAqHDXBxT6CpGRkTPFliJexpjBYB4sroJ8CiY5ZgTI2sjRBiAdGoE5ZQkfnwSoKQhWXkwo19TnbSnufr3cKO2SZkUhBqOlZcA+mgfjZ7rm2wm7RhpCR/4z8oBXDN4/xv0U5R2fLCLE=
